//
// Created by YUSUF on 27.12.2020.
//

#ifndef PAYROLLMANEGEMENTSYSTEM_SCREENTYPE_H
#define PAYROLLMANEGEMENTSYSTEM_SCREENTYPE_H

enum SCREEN {
    EMPLOYEE_SCREEN = 0,
    MANAGER_SCREEN,
    HR_SCREEN,
    IN_VALID_SCREEN
};

#endif //PAYROLLMANEGEMENTSYSTEM_SCREENTYPE_H
